name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch main
        uses: actions/checkout@v2
      - name: Sync to BunnyCDN
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ny.storage.bunnycdn.com
          ftp_username: unique-local-ipv6-com
          ftp_password: ${{ secrets.BUNNY_FTP_PASSWORD }}
          local_source_dir: "."
          dist_target_dir: ""
          delete: "true"
          exclude: "'^.git/' '^.github/' '^README.md'"
          disable_ssl_certificate_verification: false
